Add bookings
dev-Orlov/java-shareit pull request #2
Opened 2023-03-09 02:54 UTC by dev-Orlov

2023-03-09 15:39 UTC, andrew-larkin requested changes
Привет! Очень хорошо, пара правок и будем готовы двигаться дальше.

2023-03-09 15:39 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    private final ItemMapper itemMapper;
попробуй добавить в проект библиотеку mapStruct, с ней все гораздо проще будет

2023-03-09 15:39 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +
@Repository

2023-03-09 15:39 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Booking getTopByItemIdAndStartAfterOrderByStartAsc(Long itemId, LocalDateTime start);
голый объект Booking лучше из репозитория не возвращать, т.к. мы можем наткнуться на null. Оберни его в Optional, а в сервисе будем доставать его с помощью метода .orElseThrow

2023-03-09 15:39 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/exception/bookingExeption/IncorrectBooking.java
> +public class IncorrectBooking extends RuntimeException {
тоже добавь в название Exception

2023-03-10 13:58 UTC, dev-Orlov commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +
✅

2023-03-10 13:59 UTC, dev-Orlov commented on src/main/java/ru/practicum/shareit/exception/bookingExeption/IncorrectBooking.java
> +public class IncorrectBooking extends RuntimeException {
✅

2023-03-10 14:40 UTC, dev-Orlov commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Booking getTopByItemIdAndStartAfterOrderByStartAsc(Long itemId, LocalDateTime start);
orElseThrow не подойдет. Ведь если выбрасывать исключение каждый раз, когда у сущности нет бронирований, то невозможно будет получить сущность без бронирования

2023-03-10 14:55 UTC, dev-Orlov commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Booking getTopByItemIdAndStartAfterOrderByStartAsc(Long itemId, LocalDateTime start);
✅

2023-03-10 14:58 UTC, dev-Orlov commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +    private final ItemMapper itemMapper;
Если помнишь, в прошлом ТЗ ты также просил добавить mapStruct. Но когда я добавил, все тесты в постмане продолжали работать, а тесты на гите крашились. Я это пытался поправить и чуть до конца все не сломал, пришлось откатываться к рабочему коммиту. 

Насколько помню, там какой-то конфликт был с зависимостями именно при онлайн проверке. И ты сказал, что в следующих спринтах будет в ТЗ инструкция по mapStruct (могу ошибаться). Допускаю, что я сам криво что-то сделал, но так и не разобрался, в чем проблема, учитывая, что локально все работало.

2023-03-15 10:37 UTC, merged